"""Generate deterministic healthy/diseased fruit visuals for Gazebo."""

import copy
import hashlib
import json
import math
import os
from pathlib import Path
import random
import shutil
import tempfile
import xml.etree.ElementTree as ET


TREE_SCALE = 1.8 / 2.2833495
EXPECTED_FRUIT_COUNT = 134


def _face_vertices(line, vertex_count):
    indices = []
    for token in line.split()[1:]:
        value = int(token.split('/', 1)[0])
        indices.append(value - 1 if value > 0 else vertex_count + value)
    return indices


def _fruit_components(lines):
    vertex_count = sum(line.startswith('v ') for line in lines)
    faces = [line for line in lines if line.startswith('f ')]
    parent = list(range(vertex_count))

    def find(value):
        while parent[value] != value:
            parent[value] = parent[parent[value]]
            value = parent[value]
        return value

    def union(left, right):
        left_root, right_root = find(left), find(right)
        if left_root != right_root:
            parent[right_root] = left_root

    face_vertices = []
    for face in faces:
        vertices = _face_vertices(face, vertex_count)
        if not vertices:
            raise ValueError('fruit OBJ contains an empty face')
        if any(index < 0 or index >= vertex_count for index in vertices):
            raise ValueError('fruit OBJ face references an invalid vertex')
        for vertex in vertices[1:]:
            union(vertices[0], vertex)
        face_vertices.append(vertices)

    grouped = {}
    for face, vertices in zip(faces, face_vertices):
        grouped.setdefault(find(vertices[0]), []).append(face)
    return [grouped[key] for key in sorted(grouped)]


def _write_obj(path, source_lines, faces, material_name, material_file):
    geometry = [
        line for line in source_lines
        if line.startswith(('v ', 'vt ', 'vn '))
    ]
    content = [
        '# Generated by wvcsc_simulation.orchard_assets\n',
        f'mtllib {material_file}\n',
        f'o {material_name}\n',
        *geometry,
        f'usemtl {material_name}\n',
        *faces,
    ]
    path.write_text(''.join(content), encoding='utf-8')


def _write_material(path, name, diffuse):
    red, green, blue = diffuse
    path.write_text(
        '# Generated fruit material\n'
        f'newmtl {name}\n'
        'Ka 0.15 0.15 0.15\n'
        f'Kd {red:.2f} {green:.2f} {blue:.2f}\n'
        'Ks 0.20 0.20 0.20\n'
        'Ns 24.0\n'
        'illum 2\n',
        encoding='utf-8',
    )


def _tree_seed(seed, tree_name):
    digest = hashlib.sha256(f'{seed}:{tree_name}'.encode()).digest()
    return int.from_bytes(digest[:8], byteorder='big')


def _write_tree_model(
        model_dir, source_sdf, tree_mesh_uri, healthy_mesh_uri,
        diseased_mesh_uri):
    model_dir.mkdir(parents=True, exist_ok=True)
    root = ET.parse(source_sdf).getroot()
    model = root.find('model')
    model.set('name', model_dir.name)
    link = model.find('link')
    visuals = {visual.get('name'): visual for visual in link.findall('visual')}
    tree_visual = visuals['tree_visual']
    healthy_visual = visuals['apples_visual']
    healthy_visual.set('name', 'healthy_apples_visual')
    tree_visual.find('./geometry/mesh/uri').text = tree_mesh_uri
    healthy_visual.find('./geometry/mesh/uri').text = healthy_mesh_uri
    diseased_visual = copy.deepcopy(healthy_visual)
    diseased_visual.set('name', 'diseased_apples_visual')
    diseased_visual.find('./geometry/mesh/uri').text = diseased_mesh_uri
    link.append(diseased_visual)
    ET.indent(root, space='  ')
    ET.ElementTree(root).write(
        model_dir / 'model.sdf', encoding='utf-8', xml_declaration=True)
    (model_dir / 'model.config').write_text(
        '<?xml version="1.0"?>\n'
        '<model>\n'
        f'  <name>{model_dir.name}</name>\n'
        '  <version>1.0</version>\n'
        '  <sdf version="1.6">model.sdf</sdf>\n'
        '</model>\n',
        encoding='utf-8',
    )


def generate_orchard_assets(world_path, apple_tree_dir, seed=42,
                            diseased_ratio=0.20, output_dir=None):
    """Return a generated world with a deterministic disease pattern."""
    world_path = Path(world_path).resolve()
    apple_tree_dir = Path(apple_tree_dir).resolve()
    seed = int(seed)
    diseased_ratio = float(diseased_ratio)
    if not math.isfinite(diseased_ratio) or not 0.0 <= diseased_ratio <= 1.0:
        raise ValueError('diseased_fruit_ratio must be between 0.0 and 1.0')

    ratio_tag = f'{diseased_ratio:.6f}'.rstrip('0').rstrip('.')
    destination = (
        Path(output_dir) if output_dir else
        Path(tempfile.gettempdir()) / f'wvcsc_orchard_{seed}_{ratio_tag}'
    )
    destination.parent.mkdir(parents=True, exist_ok=True)
    staging = Path(tempfile.mkdtemp(
        prefix=f'.{destination.name}_', dir=destination.parent))
    try:
        models_dir = staging / 'models'
        models_dir.mkdir()
        source_obj = apple_tree_dir / 'meshes' / 'apple_tree_apples.obj'
        source_lines = source_obj.read_text(
            encoding='utf-8').splitlines(keepends=True)
        components = _fruit_components(source_lines)
        if len(components) != EXPECTED_FRUIT_COUNT:
            raise ValueError(
                f'expected {EXPECTED_FRUIT_COUNT} fruits, found {len(components)}')
        diseased_count = int(len(components) * diseased_ratio + 0.5)

        world_tree = ET.parse(world_path)
        manifest = {
            'seed': seed,
            'diseased_fruit_ratio': diseased_ratio,
            'tree_scale': TREE_SCALE,
            'fruit_count_per_tree': len(components),
            'trees': {},
        }
        for include in world_tree.getroot().findall('.//include'):
            uri = include.find('uri')
            name_node = include.find('name')
            if uri is None or uri.text != 'model://apple_tree' or name_node is None:
                continue
            tree_name = name_node.text.strip()
            model_name = f'orchard_{tree_name}'
            model_dir = models_dir / model_name
            model_dir.mkdir()
            diseased = set(random.Random(_tree_seed(seed, tree_name)).sample(
                range(len(components)), diseased_count))
            healthy = set(range(len(components))) - diseased
            healthy_faces = [
                face for index in sorted(healthy) for face in components[index]
            ]
            diseased_faces = [
                face for index in sorted(diseased) for face in components[index]
            ]
            healthy_obj = model_dir / 'healthy_apples.obj'
            diseased_obj = model_dir / 'diseased_apples.obj'
            _write_obj(healthy_obj, source_lines, healthy_faces,
                       'HealthyFruit', 'healthy_apples.mtl')
            _write_obj(diseased_obj, source_lines, diseased_faces,
                       'DiseasedFruit', 'diseased_apples.mtl')
            _write_material(
                model_dir / 'healthy_apples.mtl',
                'HealthyFruit', (0.90, 0.02, 0.02))
            _write_material(
                model_dir / 'diseased_apples.mtl',
                'DiseasedFruit', (1.00, 0.80, 0.00))
            _write_tree_model(
                model_dir,
                apple_tree_dir / 'model.sdf',
                (apple_tree_dir / 'meshes' / 'apple_tree.obj').as_uri(),
                f'model://{model_name}/healthy_apples.obj',
                f'model://{model_name}/diseased_apples.obj',
            )
            uri.text = f'model://{model_name}'
            manifest['trees'][tree_name] = {
                'healthy_count': len(healthy),
                'diseased_count': len(diseased),
                'diseased_components': sorted(diseased),
            }

        if not manifest['trees']:
            raise ValueError('orchard world does not include any apple_tree models')
        ET.indent(world_tree.getroot(), space='  ')
        generated_world = staging / 'orchard.world'
        world_tree.write(generated_world, encoding='utf-8', xml_declaration=True)
        (staging / 'manifest.json').write_text(
            json.dumps(manifest, indent=2, sort_keys=True), encoding='utf-8')

        if destination.exists():
            shutil.rmtree(destination)
        os.replace(staging, destination)
        return destination / 'orchard.world'
    except Exception:
        shutil.rmtree(staging, ignore_errors=True)
        raise
