wvcsc_spray_simulator:
  ros__parameters:
    action_name: /spray/execute
    active_topic: /spray/simulated_active
    motion_locked_topic: /motion_control/locked
    min_duration: 0.2
    max_duration: 10.0
